---
inputdirs:
    - /fast/groups/ag_schmueck/work/NGSData/Illumina/221208-P1696 # source of fastq files (subfolders allowed) [or bam files in case of rerun]
workdir: /fast/users/szyskam_c/scratch/projects/LungWES # here your results are created
envs: envs/mamba # the folder of the env-files (MacOS requires different environments)
samples: # here go all your samples
    samplesheet: sheets/221208_LungWES_sheet.csv
    reads:
        - R1
        - R2
    umi_barcode: index # suffix for the fastq containing the umi-barcode
setup:
    cleanup:
        run: False
        keep_only_final_bam: True
    run: PE   # SE run is not implemented
    phred: 33
    library: SureSelect  # have to be found at bed_files/SureSelect/<build>/SS_<library_version>_<build>_<Padded | Covered>[_nochr].bed
    library_version: HAEv8
    platform: illumina
    Flowcell: BHMG7JD
    Instrument: A00643
    platform_unit: A00643.BHMG7JD
    UMI: True # if UMI information should be used in pipeline
    # if UMI_filter is true: deduplication is substituted with the UMI-filter pipeline
    # else: umi-aware deduplication is used 
#### ABSOLUTE PATHS ############
paths:
    mystatic: /fast/groups/ag_schmueck/work/ref/
    bihstatic: /fast/projects/cubit/current/static_data
#### REF SECTION ###############
ref:
    build: hg38
    hg19:
        genome_path: genome/gatk/b37
        genome: genome/gatk/b37/human_g1k_v37.fasta
        genome_split: genome/gatk/b37/split
        candidates: /fast/users/szyskam_c/work/utils/bulltools/known_sites/candidate_genes_aml.txt
        dbsnp: annotation/gatk/b37/dbsnp_138.b37.vcf
        dbsnp_all: annotation/gatk/b37/All_20180423.vcf
        dbsnp_common: annotation/gatk/b37/common_all_20180423.vcf
        gold_standard_indels: annotation/gatk/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
        phase1k_indels: annotation/gatk/b37/1000G_phase1.indels.b37.vcf
        # bed_file: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Covered_nochr.bed
        # bed_file_pad: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Padded_nochr.bed
    hg38:
        genome_path: genome/
        genome: genome/hg38.fasta
        genome_split: genome/split
        dbsnp: annotation/gatk/dbSNP138.hg38.vcf
        dbsnp_all: annotation/gatk/All_20180418.vcf
        dbsnp_common: annotation/gatk/common_all_20180418.vcf
        gold_standard_indels: annotation/gatk/Mills_and_1000G_gold_standard.indels.hg38.vcf
        phase1k_indels: annotation/gatk/1000G_phase1.snps.high_confidence.hg38.vcf # seems to work instead of indels (acc. to GATK blog: https://gatkforums.broadinstitute.org/gatk/discussion/6800/known-sites-for-indel-realignment-and-bqsr-in-hg38-bundle)
        bed_file: bed_files/SureSelect/SS_HAEv8_hg38_Covered.bed
        bed_file_pad: bed_files/SureSelect/SS_HAEv8_hg38_Padded.bed
        bed_file_targets: bed_files/SureSelect/SS_HAEv8_hg38_Targets.txt
#### TOOLS SECTION ##############
tools:
    gatk: gatk # 
    gatk3: java -jar /fast/users/szyskam_c/work/utils/gatk3.8/GenomeAnalysisTK.jar -T
    # annovar: perl /fast/users/szyskam_c/tools/annovar2018
    annovar: perl /fast/users/szyskam_c/tools/annovar2019
fastq:
    threads: 20
    split_factor: 8 # split fastqs and run pipeline on split files --> merge before deduplication
qc:
    samplefactor: 1
ubamXT:
    threads: 8
    use_jdk: True # use_jdk_in/deflater to avoid SIGSEV error
alignment:
    tool: bwa
    threads: 16
    clip_overlap: False
    strategy: MostDistant  # alignment strategy for MergeBamAlignment
    use_jdk: True
bamindex:
    threads: 2
tag_bam: # needs enough RAM for loading entire uncompressed index fastq into memory
    run: True
    max_mem: 30g # memory for java VM (30g seems neccessary - needs to be smaller than threads * vmem/thread)
merge_bam:
    threads: 20
resplit_bam:
    threads: 6
dedup:
    threads: 4
dedup_umi:
    max_mem: 10g
    keep_dups: True # keep dups if you want to perform UMI-correction
realignGATK:
    max_mem: 20G
    threads: 16
recalib:
    run: True
    threads: 12
    known_sites: dbsnp_common   # which dbsnp database to use beside gold_standard_indels and phase1k
UMI_filter:
    run: False # if False and setup-->UMI is True, run umi-dedup
    min_reads:  1 # for WES-data, 1 is good; for targeted >3  counts for all fgbio tools
    group:
        threads: 10
        mem: 2G
        group_strategy: adjacency
        min_base_Q: 20
        min_map_q: 20
        edits: 1  # 1 edit in a umi-node should be ok
    call:
        threads: 6
        mem: 6G
        error_rate_pre_umi: 45
        error_rate_post_umi: 40
        min_input_Q: 20 # input base quality (10 is default; IDT says 30)
    remap:
        threads: 10
        mem: 6G
        clip_overlap: True
        clip_adapters: True
    filter:
        threads: 6
        mem: 6G
        max_error_rate_per_read: 0.05
        max_error_rate_per_base: 0.1
        min_Q: 30 # input base quality
        max_no_call: 0.1 # fraction of reads filtered per M/e
cover_bed:
    histo_steps: "0 1 10 15 50 100 120 200 500 1000 1500 2000 2500"
bam_metrix:
    run: False
    threads: 6
